apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  namespace: devopsquiz-app
  labels:
    app: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - image: :982f738373f5f67e8c93d3e25ab659b74c1c0d72
          name: "backend-container"
          ports:
            - protocol: "TCP"
              containerPort: 8000

          livenessProbe:
            httpGet:
              path: "/health"
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 15

          readinessProbe:
            httpGet:
              path: "/ready"
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
            
          resources:
            requests:
              memory: "100Mi"
              cpu: "500m"
              
            limits:
              memory: "150Mi"
              cpu: "700m"

          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: devopsquiz-app-secrets