apiVersion: batch/v1
kind: Job
metadata:
  name: backend-mig-job
  namespace: devopsquiz-app
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  
spec:
  backoffLimit: 2

  template:
    metadata:
        name: backend-mig-job
    spec:
      containers:
        - name: migration-container
          image: :982f738373f5f67e8c93d3e25ab659b74c1c0d72
          command: ["./migrate.sh"]

          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: devopsquiz-app-secrets
      restartPolicy: OnFailure