apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: three-tier-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: ZGV2b3BzX2xlYXJuaW5n
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvZGV2b3BzX2xlYXJuaW5n