# Drop down: with choices for each module
# Drop down: with choice to run plan or apply?
# Jobs: install terraform version; checkout repository; authenticate to AWS; run terraform init; terraform plan; terraform apply

name: eks-modular-infra-deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      TerraformModule:
        description: 'Choose terraform module to deploy'
        required: true
        type: choice
        options:
          - app-infra
          - eks-core-infra
          - k8s-services

jobs:
  infra-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.OIDC_AWS_ROLE }}   # we configure the terraform output as a github variable and use in the workflow
          role-session-name: Build-eks-infra-session

      - name: Install Terraform on runner
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15"

      - name: Terraform init
        working-directory: ${{ inputs.TerraformModule }}
        run: terraform init -input=false
      
      - name: Terraform plan
        working-directory: ${{ inputs.TerraformModule }}
        run: terraform plan -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-artifact
          path: ${{ inputs.TerraformModule }}/tfplan
  
  infra-apply:
    runs-on: ubuntu-latest
    environment: dev
    needs: infra-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.OIDC_AWS_ROLE }}   # we configure the terraform output as a github variable and use in the workflow
          role-session-name: Build-eks-infra-session

      - name: Install Terraform on runner
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15"

      - name: Terraform init
        working-directory: ${{ inputs.TerraformModule }}
        run: terraform init -input=false

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-artifact
          path: ${{ inputs.TerraformModule }}
      
      - name: Terraform apply
        working-directory: ${{ inputs.TerraformModule }}
        run: terraform apply tfplan